[package]
name = "feanor-tracing"
version = "1.0.1"
edition = "2024"
authors = ["Simon Pohmann <simon@pohmann.de>"]

repository = "https://github.com/FeanorTheElf/feanor-tracing"
homepage = "https://github.com/FeanorTheElf/feanor-tracing"
keywords = ["tracing", "logging"]
readme = "Readme.md"
description = "A simple tracing subscriber that prints an overview of the current state to stdout, and ignores short or deeply nested functions."
license = "MIT"

[badges]
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["rlib"]
bench = true

[dependencies]
thread_local = "1.1.9"
tracing = "0.1.44"
tracing-core = "0.1.34"

[profile.test]
panic = "abort"